// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGs01XBhIK8D5mqOe4d5BR67PheNOEgn8',
    appId: '1:864158609969:web:e8d40395866f843525db10',
    messagingSenderId: '864158609969',
    projectId: 'sportsbuddy-fd199',
    authDomain: 'sportsbuddy-fd199.firebaseapp.com',
    storageBucket: 'sportsbuddy-fd199.appspot.com',
    measurementId: 'G-52VNL8NGBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Eu_0qitWEUULIRZCepbP1b7mgzEg3FY',
    appId: '1:864158609969:android:72a8876820919e9c25db10',
    messagingSenderId: '864158609969',
    projectId: 'sportsbuddy-fd199',
    storageBucket: 'sportsbuddy-fd199.appspot.com',
  );
}
